name: starter
on:
  push: 
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  az-cli:
    name: "azure setup"
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: az cli

    - name: print vars
      run: echo vars
    
  
